spring:
  datasource:
    url: jdbc:mysql://39.104.146.45/grape_workflow?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: jlks82lsUH@@
logging:
  level:
    root: debug
flowable:
  database-schema-update: true
  # 关闭异步，不关闭历史数据的插入就是异步的，会在同一个事物里面，无法回滚
  # 开发可开启会提高些效率，上线需要关闭
  async-executor-activate: false