spring:
  datasource:
    url: jdbc:mysql://39.104.146.45/grape_workflow?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: jlks82lsUH@@
logging:
  level:
    root: debug
flowable:
  idm:
    app:
      admin:
        user-id: admin
        password: test
